/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.view;

/**
 *
 * @author Christian
 */
public class ChatView extends javax.swing.JFrame
{

  /**
   * @return the TfIP
   */
  public javax.swing.JTextField getTfIP()
  {
    return TfIP;
  }

  /**
   * @return the SelectSC
   */
  public javax.swing.JComboBox<String> getSelectSC()
  {
    return SelectSC;
  }

  /**
   * @return the BtnConnect
   */
  public javax.swing.JToggleButton getBtnConnect()
  {
    return BtnConnect;
  }

  /**
   * @return the BtnSend
   */
  public javax.swing.JButton getBtnSend()
  {
    return BtnSend;
  }

  /**
   * @return the TAExtern
   */
  public javax.swing.JTextArea getTAExtern()
  {
    return TAExtern;
  }

  /**
   * @return the TAUser
   */
  public javax.swing.JTextArea getTAUser()
  {
    return TAUser;
  }

  /**
   * @return the TFMessage
   */
  public javax.swing.JTextField getTFMessage()
  {
    return TFMessage;
  }

  /**
   * @return the TfAdress
   */
  public javax.swing.JTextField getTfAdress()
  {
    return TfIP;
  }

  /**
   * Creates new form NewJFrame
   */
  public ChatView()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    Center = new javax.swing.JPanel();
    TAExtern = new javax.swing.JTextArea();
    TAUser = new javax.swing.JTextArea();
    South = new javax.swing.JPanel();
    TFMessage = new javax.swing.JTextField();
    jSeparator3 = new javax.swing.JSeparator();
    BtnSend = new javax.swing.JButton();
    North = new javax.swing.JPanel();
    SelectSC = new javax.swing.JComboBox<>();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel1 = new javax.swing.JLabel();
    TfIP = new javax.swing.JTextField();
    jSeparator2 = new javax.swing.JSeparator();
    BtnConnect = new javax.swing.JToggleButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Chat-Programm");

    Center.setLayout(new javax.swing.BoxLayout(Center, javax.swing.BoxLayout.LINE_AXIS));

    TAExtern.setEditable(false);
    TAExtern.setColumns(20);
    TAExtern.setRows(5);
    TAExtern.setText("Extern");
    TAExtern.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Center.add(TAExtern);

    TAUser.setEditable(false);
    TAUser.setColumns(20);
    TAUser.setRows(5);
    TAUser.setText("Benutzer");
    TAUser.setToolTipText("");
    TAUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    Center.add(TAUser);
    TAUser.getAccessibleContext().setAccessibleParent(jScrollPane1);

    jScrollPane1.setViewportView(Center);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
    jScrollPane1.getAccessibleContext().setAccessibleParent(this);

    TFMessage.setColumns(25);
    South.add(TFMessage);
    South.add(jSeparator3);

    BtnSend.setText("Send");
    South.add(BtnSend);

    getContentPane().add(South, java.awt.BorderLayout.SOUTH);
    South.getAccessibleContext().setAccessibleParent(this);

    SelectSC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Server", "Client" }));
    North.add(SelectSC);
    North.add(jSeparator1);

    jLabel1.setText("IP:");
    North.add(jLabel1);

    TfIP.setColumns(15);
    TfIP.setText("127.0.0.1");
    TfIP.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        TfIPActionPerformed(evt);
      }
    });
    North.add(TfIP);
    North.add(jSeparator2);

    BtnConnect.setText("Connect");
    North.add(BtnConnect);

    getContentPane().add(North, java.awt.BorderLayout.NORTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void TfIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TfIPActionPerformed
  {//GEN-HEADEREND:event_TfIPActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_TfIPActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(ChatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new ChatView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton BtnConnect;
  private javax.swing.JButton BtnSend;
  private javax.swing.JPanel Center;
  private javax.swing.JPanel North;
  private javax.swing.JComboBox<String> SelectSC;
  private javax.swing.JPanel South;
  private javax.swing.JTextArea TAExtern;
  private javax.swing.JTextArea TAUser;
  private javax.swing.JTextField TFMessage;
  private javax.swing.JTextField TfIP;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  // End of variables declaration//GEN-END:variables
}
